<?php
	include 'include/sessionHead.php';
	if(isset($_POST['submit'])){
		$query = "DROP TABLE TASK_ELEMENT;";
		$query.="DROP TABLE TASK;";
		$query.="DROP TABLE TEAM_MEMBER;";
		$query.="DROP TABLE MEMBER;";
		$query.="DROP TABLE TEAM;";
		$query.="COMMIT;";
		$query.="CREATE TABLE MEMBER
			(
			MEMBER_ID     INT NOT NULL AUTO_INCREMENT,
			SURNAME       VARCHAR (20) NOT NULL ,
			FORENAME      VARCHAR (20) NOT NULL ,
			EMAIL_ADDRESS VARCHAR (30) NOT NULL ,
			PRIMARY KEY (MEMBER_ID)
			)
			AUTO_INCREMENT=100
			;";
		$query.="CREATE UNIQUE INDEX MEMBER__IDX ON MEMBER
		  (
			MEMBER_ID ASC
		  )
		  ;";
		  $query.="CREATE INDEX MEMBER__IDXv1 ON MEMBER
			( SURNAME ASC , FORENAME ASC
			) ;";
		  $query.="CREATE INDEX MEMBER__IDXv2 ON MEMBER
			( FORENAME ASC
			) ;";

		$query.="CREATE TABLE TASK
		  (
			TASK_ID                  INT NOT NULL AUTO_INCREMENT,
			TASK_NAME                VARCHAR (30) NOT NULL ,
			TEAM_ID                  INT NOT NULL ,
			MEMBER_ID                INT NOT NULL ,
			START_DATE               DATE NOT NULL ,
			EXPECTED_COMPLETION_DATE DATE NOT NULL ,
			TASK_STATUS              VARCHAR (9) NOT NULL ,
			PRIMARY KEY (TASK_ID)
		  )
		  AUTO_INCREMENT=100
		  ;";
		$query.="CREATE UNIQUE INDEX TASK__IDX ON TASK ( TASK_ID ASC ) ;
		  CREATE INDEX TASK__IDXv1 ON TASK
			( TEAM_ID ASC , MEMBER_ID ASC
			) ;";
		  $query.="CREATE INDEX TASK__IDXv2 ON TASK
			( MEMBER_ID ASC
			) ;";
		$query.="CREATE UNIQUE INDEX TASK__IDXv3 ON TASK
		  (
			TASK_NAME ASC
		  )
		  ;";
		$query.="ALTER TABLE TASK ADD CONSTRAINT TASK_STATUS_CHECK CHECK (TASK_STATUS IN ('completed','abandoned','allocated')) ;";

		$query.="CREATE TABLE TASK_ELEMENT
		  (
			ELEMENT_ID       INT NOT NULL AUTO_INCREMENT,
			TASK_ID          INT NOT NULL ,
			TASK_DESCRIPTION VARCHAR (1000) NOT NULL ,
			PRIMARY KEY (ELEMENT_ID)
		  )
		  AUTO_INCREMENT=100
		  ;";
		$query.="CREATE UNIQUE INDEX TASK_ELEMENT__IDX ON TASK_ELEMENT
		  (
			ELEMENT_ID ASC
		  )
		  ;";
		  $query.="CREATE INDEX TASK_ELEMENT__IDXv1 ON TASK_ELEMENT
			( TASK_ID ASC
			) ;";

		$query.="CREATE TABLE TEAM
		  (
			TEAM_ID   INT NOT NULL AUTO_INCREMENT,
			TEAM_NAME VARCHAR (30) NOT NULL ,
			PRIMARY KEY (TEAM_ID)
		  )
		  AUTO_INCREMENT=100
		  ;";
		$query.="CREATE UNIQUE INDEX TEAM__IDX ON TEAM
		  (
			TEAM_ID ASC
		  )
		  ;";
		$query.="CREATE UNIQUE INDEX TEAM__IDXv1 ON TEAM
		  (
			TEAM_NAME ASC
		  )
		  ;";

		$query.="CREATE TABLE TEAM_MEMBER
		  (
			TEAM_ID   INT NOT NULL ,
			MEMBER_ID INT NOT NULL
		  )
		  ;";
		$query.="CREATE UNIQUE INDEX TEAM_MEMBER__IDX ON TEAM_MEMBER
		  (
			TEAM_ID ASC , MEMBER_ID ASC
		  )
		  ;";
		  $query.="CREATE INDEX TEAM_MEMBER__IDXv1 ON TEAM_MEMBER
			( MEMBER_ID ASC
			) ;";
		$query.="ALTER TABLE TEAM_MEMBER ADD CONSTRAINT TEAM_MEMBER_PK PRIMARY KEY ( TEAM_ID, MEMBER_ID ) ;";

		$query.="ALTER TABLE TASK_ELEMENT ADD CONSTRAINT TASK_ELEMENT_TASK_FK FOREIGN KEY ( TASK_ID ) REFERENCES TASK ( TASK_ID ) 
		ON DELETE CASCADE;";

		$query.="ALTER TABLE TASK ADD CONSTRAINT TASK_TEAM_MEMBER_FK FOREIGN KEY ( TEAM_ID, MEMBER_ID ) REFERENCES TEAM_MEMBER ( TEAM_ID, MEMBER_ID ) 
		ON DELETE CASCADE;";

		$query.="ALTER TABLE TEAM_MEMBER ADD CONSTRAINT TEAM_MEMBER_MEMBER_FK FOREIGN KEY ( MEMBER_ID ) REFERENCES MEMBER ( MEMBER_ID ) 
		ON DELETE CASCADE;";

		$query.="ALTER TABLE TEAM_MEMBER ADD CONSTRAINT TEAM_MEMBER_TEAM_FK FOREIGN KEY ( TEAM_ID ) REFERENCES TEAM ( TEAM_ID ) 
		ON DELETE CASCADE;";

		$query.="COMMIT;";

		$query.="INSERT INTO TEAM (TEAM_NAME) VALUES ('alpha');";
	if ($res = mysqli_multi_query($connection, $query)){
		echo "Database creation successful!";
	}else{
		echo "Database creation unsuccessful";
	}
	}
?>